import {
  Bot,
  Pencil,
  Crown,
  Briefcase,
  DollarSign,
  Wrench,
  Megaphone,
  Search,
  ShieldCheck,
  BarChart3,
  Palette,
  Smartphone,
  Rocket,
  Handshake,
  PenTool,
  Code,
  UserCheck,
  Scale,
  Sparkles,
  Lightbulb,
  Compass,
  Cpu,
  Feather,
  Flame,
  Heart,
  Coffee,
  Mic,
  Camera,
  Hammer,
  Target,
  Zap,
  Book,
  FlaskConical,
  Gavel,
  Globe,
  Headphones,
  Leaf,
  Music,
  Stethoscope,
  Wand2,
  type LucideIcon,
} from "lucide-react";

// Full map used by catalog lookup. Lucide keys are the icon name strings.
export const ICON_CATALOG: Record<string, LucideIcon> = {
  Bot,
  Pencil,
  Crown,
  Briefcase,
  DollarSign,
  Wrench,
  Megaphone,
  Search,
  ShieldCheck,
  BarChart3,
  Palette,
  Smartphone,
  Rocket,
  Handshake,
  PenTool,
  Code,
  UserCheck,
  Scale,
  Sparkles,
  Lightbulb,
  Compass,
  Cpu,
  Feather,
  Flame,
  Heart,
  Coffee,
  Mic,
  Camera,
  Hammer,
  Target,
  Zap,
  Book,
  FlaskConical,
  Gavel,
  Globe,
  Headphones,
  Leaf,
  Music,
  Stethoscope,
  Wand2,
};

// Curated picker subset, ordered for the grid.
export const ICON_PICKER_KEYS: string[] = [
  "Bot",
  "Pencil",
  "Crown",
  "Briefcase",
  "DollarSign",
  "Wrench",
  "Megaphone",
  "Search",
  "ShieldCheck",
  "BarChart3",
  "Palette",
  "Smartphone",
  "Rocket",
  "Handshake",
  "PenTool",
  "Code",
  "UserCheck",
  "Scale",
  "Sparkles",
  "Lightbulb",
  "Compass",
  "Cpu",
  "Feather",
  "Flame",
  "Heart",
  "Coffee",
  "Mic",
  "Camera",
  "Hammer",
  "Target",
  "Zap",
  "Book",
  "FlaskConical",
  "Gavel",
  "Globe",
  "Headphones",
  "Leaf",
  "Music",
  "Stethoscope",
  "Wand2",
];

// Default icon per-slug, used when an agent has no explicit iconKey set.
export const DEFAULT_ICONS_BY_SLUG: Record<string, LucideIcon> = {
  general: Bot,
  editor: Pencil,
  ceo: Crown,
  coo: Briefcase,
  cfo: DollarSign,
  cto: Wrench,
  "content-marketer": Megaphone,
  seo: Search,
  "seo-specialist": Search,
  qa: ShieldCheck,
  "qa-agent": ShieldCheck,
  sales: BarChart3,
  "sales-agent": BarChart3,
  "product-manager": Briefcase,
  "ux-designer": Palette,
  "data-analyst": BarChart3,
  "social-media": Smartphone,
  "growth-marketer": Rocket,
  "customer-success": Handshake,
  copywriter: PenTool,
  devops: Code,
  developer: Code,
  "people-ops": UserCheck,
  legal: Scale,
  researcher: Search,
};

export function getIconByKey(key: string | undefined | null): LucideIcon | null {
  if (!key) return null;
  return ICON_CATALOG[key] ?? null;
}

export function resolveAgentIcon(
  slug: string,
  iconKey?: string | null
): LucideIcon {
  const explicit = getIconByKey(iconKey);
  if (explicit) return explicit;
  return DEFAULT_ICONS_BY_SLUG[slug] ?? Bot;
}
